# Basic security
# ====================================================

- name: Update APT package cache
  action: apt update_cache=yes

- name: Install mosh
  action: apt pkg=mosh state=installed

- name: Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Add deployment user
  action: user name=deploy password=$deploy_password

- name: Add authorized deploy key
  action: authorized_key user=deploy key='$FILE(~/.ssh/id_rsa.pub)'

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) NOPASSWD:ALL" state=present

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart ssh

- name: Install unattended-upgrades
  action: apt pkg=unattended-upgrades state=present

- name: Set up Postfix to relay mail
  action: command debconf-set-selections /tmp/postfix_selections

# Firewall
# ====================================================

- name: Setup ufw
  action: shell ufw allow 22

- name: Setup ufw
  action: shell ufw allow 80

- name: Setup ufw
  action: shell ufw allow 443

- name: Enable ufw
  action: shell echo 'y' | ufw enable

# Install anything essential that you need here
# ====================================================

- name: install essential packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
    - build-essential
    - wget
    - emacs
    - curl
    - git-core
    - python-setuptools
    - python-software-properties

